export * from './Main';
export * from './Login';
export * from './Register';
export * from './Splash';
export * from './City';
export * from './Cart';
export * from './Resturants';
export * from './Details';
export * from './Profile';
