export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
export const CLEAR_TO_CART = 'CLEAR_TO_CART';
export const INCREASE_ELEMENT = 'INCREASE_ELEMENT';
export const DECREASE_ELEMENT = 'DECREASE_ELEMENT';
